jwt:
  public:
    key: ${JWT_PUBLIC_KEY}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8086
  error:
    include-message: always

cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://fintech-core-frontend.vercel.app}

paypal:
  client:
    id: ${PAYPAL_CLIENT_ID}
    secret: ${PAYPAL_CLIENT_SECRET}
  mode: ${PAYPAL_MODE:sandbox}
  base-url: ${PAYPAL_BASE_URL:https://api-m.sandbox.paypal.com}
  brandName: Fintech Core
  landingPage: LOGIN
  returnUrl: ${FRONTEND_URL:http://localhost:3000}/payment-success
  cancelUrl: ${FRONTEND_URL:http://localhost:3000}/payment-cancel
  userAction: PAY_NOW

stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET} 