services:
  - type: web
    name: fintech-transaction-service
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_DOMAIN
        value: https://your-frontend-url.vercel.app
    healthCheckPath: /actuator/health
    autoDeploy: true 