services:
  postgres:
    image: 'postgres:13'
    environment:
      - 'POSTGRES_DB=customer_db'
      - 'POSTGRES_PASSWORD=saas_password'
      - 'POSTGRES_USER=saas_user'
    ports:
      - '5433:5432'
    networks:
      - customer-network

  customer-service:
    image: customer-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer_db
      SPRING_DATASOURCE_USERNAME: saas_user
      SPRING_DATASOURCE_PASSWORD: saas_password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - customer-network

networks:
  customer-network:
    driver: bridge